name: Build

on: [push, pull_request]

jobs:
  build-binary:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Build binary
      run: |
        docker build -t re_nfpii_builder .
        docker run --rm -v ${PWD}:/project re_nfpii_builder make dist
    - uses: actions/upload-artifact@v2
      with:
       name: re_nfpii
       path: dist/*
